-- Data migration for water-refill businesses
-- Adding 3 water refill stations in San Francisco

-- Generate UUIDs for water-refill businesses
INSERT INTO businesses (
    id, 
    business_id, 
    name, 
    description, 
    address, 
    phone, 
    website, 
    email, 
    rating, 
    review_count, 
    category, 
    city, 
    state, 
    services, 
    verified, 
    hours, 
    image, 
    established, 
    site_id, 
    status, 
    created_at, 
    updated_at, 
    premium,
    latitude,
    longitude
) VALUES 
(
    'wr-sf-001',
    'water-refill-san-francisco-01',
    'AquaPure Station - Downtown',
    'Premium water refill station with advanced filtration and purification systems.',
    '100 Main Street, San Francisco, CA 94102',
    '(415) 555-0123',
    'https://aquapure.com',
    'contact@aquapure.com',
    4.6,
    189,
    'water-refill',
    'san-francisco',
    'California',
    '["Purified Water","Alkaline Water","Distilled Water","Reverse Osmosis"]',
    1,
    '{"monday":"24 hours","tuesday":"24 hours","wednesday":"24 hours","thursday":"24 hours","friday":"24 hours","saturday":"24 hours","sunday":"24 hours"}',
    '/images/businesses/water-refill-1.jpg',
    2015,
    'near-me-us',
    'active',
    datetime('now'),
    datetime('now'),
    0,
    37.7749,
    -122.4194
),
(
    'wr-sf-002',
    'water-refill-san-francisco-02',
    'Crystal Clear Refill - Mission',
    'Family-owned water refill station serving the community for over 10 years.',
    '101 Mission Street, San Francisco, CA 94105',
    '(415) 555-0124',
    'https://crystalclear.com',
    'info@crystalclear.com',
    4.5,
    156,
    'water-refill',
    'san-francisco',
    'California',
    '["Spring Water","Electrolyte Water","pH Balanced Water","Bulk Water Sales"]',
    1,
    '{"monday":"6:00 AM - 10:00 PM","tuesday":"6:00 AM - 10:00 PM","wednesday":"6:00 AM - 10:00 PM","thursday":"6:00 AM - 10:00 PM","friday":"6:00 AM - 11:00 PM","saturday":"7:00 AM - 11:00 PM","sunday":"8:00 AM - 9:00 PM"}',
    '/images/businesses/water-refill-2.jpg',
    2013,
    'near-me-us',
    'active',
    datetime('now'),
    datetime('now'),
    0,
    37.7849,
    -122.4094
),
(
    'wr-sf-003',
    'water-refill-san-francisco-03',
    'Blue Drop Water - Sunset',
    'Neighborhood water refill station with competitive prices and quality water.',
    '102 Sunset Blvd, San Francisco, CA 94116',
    '(415) 555-0125',
    'https://bluedrop.com',
    'service@bluedrop.com',
    4.0,
    98,
    'water-refill',
    'san-francisco',
    'California',
    '["Mineral Water","Water Testing","Purified Water","Alkaline Water"]',
    0,
    '{"monday":"7:00 AM - 9:00 PM","tuesday":"7:00 AM - 9:00 PM","wednesday":"7:00 AM - 9:00 PM","thursday":"7:00 AM - 9:00 PM","friday":"7:00 AM - 10:00 PM","saturday":"8:00 AM - 10:00 PM","sunday":"9:00 AM - 8:00 PM"}',
    '/images/businesses/water-refill-3.jpg',
    2018,
    'near-me-us',
    'active',
    datetime('now'),
    datetime('now'),
    0,
    37.7649,
    -122.4294
);
